name: Bug report
description: Use this template for reporting bugs/issues.
labels:
  - "kind/bug"
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: textarea
    id: what-happened
    attributes:
      label: Describe issue
      description: |
        Also tell us what did you expect to happen?
      placeholder: |
        Describe issue
    validations:
      required: true
  - type: input
    id: repo
    attributes:
      label: Link to GitHub repository
      description: |
        Provide link to GitHub repository, you can skip it if the repository is private or you don't have it on GitHub, otherwise please provide it as it might help us troubleshoot problem
      placeholder: |
        https://github.com/thuongtruong109/locanet
    validations:
      required: false
  - type: textarea
    id: additional-info
    attributes:
      label: Additional information
      placeholder: |
        Additional information that doesn't fit elsewhere
    validations:
      required: false
